name: aprendizaje_profundo
channels:
   - defaults
   - anaconda
   - conda-forge
   - pytorch
dependencies:
   - python=3.7.3
   - numpy=1.17.0
   - scipy=1.3.1
   - ipywidgets
   - pillow
   - joblib=0.13.2
   - pandas=0.25.0
   - matplotlib=3.1.1
   - seaborn=0.9.0
   - jupyterlab
   - scikit-learn=0.21.3
   - pytorch-cpu
   - torchvision-cpu
   - pip:
     - tensorflow
     - tensorboard
     - tensorflow_probability
     - tensorflow-addons
     - tensorflow_hub
     - tensorflow-datasets
     